#!/bin/bash

PID=$(pgrep offlineimap)
CONNECTED=$(nmcli -t -f STATE dev | grep \^connected | uniq)

# if there is no active network connection exit
[[ -z "$CONNECTED" ]] && exit 0

# the only time offlineimap has been still running after 3 minutes for 
# me is if it's frozen... we'll kill it and resync
[[ -n "$PID" ]] && kill $PID

offlineimap -o -u Noninteractive.Quiet &>/dev/null 

exit 0
