#!/bin/bash

name=""
domain="home"
ram="128"
size="4"
bridge="virbr0"
mirror="http://mirror.aarnet.edu.au/pub/ubuntu/archive/"
varent="natty"
distro="ubuntu"
while getopts  "n:v:d:s:r:" flag
do
  case "$flag" in
      n)
	  name="$OPTARG"
	  ;;
      v)
	  varent="$OPTARG"
	  ;;
      d)
	  distro="$OPTARG"
	  ;;
      r)
	  ram="$OPTARG"
	  ;;
      s)
	  size="$OPTARG"
	  ;;
      *)
	  echo "Usage $(basename $0) -n <name> -s <size> -r <ram> -v <varent>"
	  echo "varent examples: natty, oneiric"
	  exit 1
  esac
done
if [ -z "$name" ]
then
    echo "you must specify a name"
    exit 1
fi

preseed="http://10.42.10.1/$varent.cfg"
os="$distro$varent"

sudo virt-install -n $name -r $ram --vcpus=1 \
    --os-variant=$os \
    --disk /var/lib/libvirt/images/$name.img,size=$size \
    --noautoconsole \
    --graphics vnc \
    -w bridge=$bridge,model=virtio \
    -l $mirror/dists/$varent/main/installer-amd64/ \
    -x "DEBIAN_FRONTEND=text console=ttyS0,115200 auto language=en console-setup/ask_detect=false console-setup/modelcode=SKIP keyboard-configuration/layoutcode=us console-keymaps-at/keymap=us country=AU locale=en_AU.UTF-8 DEBCONF_PRIORITY=critical preseed/url=$preseed hostname=$name domain=$domain"
if [ $? -ne 0 ]
then
    echo "failed to kickoff virt-install"
    exit 1
fi

virsh console $name
